;;union-atom contains function ->(12345) 1

;; impliment union-atom -> eqivalent to set union function

;;impliment function to find unique sibling using subtract-atom

 
 (person mary 64 female)
(person smith 20 female)
(person lisa 27 female)
(person adam 30 male)
(person lily 10 female)


;;!(union-atom(11 12 34 56 78) (40 45 84 12))

(=(union ($x) ($y) )(union-atom($x) ($y)) )

!(union (1) (3))